### ISSUE TITLE
Issue with Waiting to Mount...waiting infinitely

### ISSUE THREAD

**Issue by wicadmin** [msh100/acd-docker#1]
Hello,
I ran this stack, however, it is infinitely waiting for mount. Also, noticed that acd-decrypted is not created. Is this still supposed to work?

It appears that for the two images that have the wait-for-mount in the mount.sh files, there isn't anything mounting those mount points into those containers. Perhaps I missed something important.

**Comment by msh100** [comment]
hey @2devnull thanks for raising an issue.

This was all made before docker 1.10 (shared mount namespace support) in the intention of being ready by February however I never finished the project.

I have had a **lot** of interest recently so may continue soon to fix the issues which exist here.

As for now I don't know how much of this does or does not work but I will resolve it when I have some spare time.

**Comment by wicadmin** [comment]
Appreciate it. If you can point me on what the design should look like given the shared mount namespace support, I'll be interested in helping out.

**Comment by wicadmin** [comment]
Hey Marcus, just checking in if you were able to look into updating this for the latest docker. Glad to help if I can.

**Comment by msh100** [comment]
@2devnull I intend to put this all in a single container asap and use encfs `--reverse` mounting for local data, I will update you when there's a container on the docker hub
